project_id = "twfkfyahakmvnpsvqurf"

[functions.generate-quiz]
verify_jwt = false

[functions.fetch-transcript]
verify_jwt = false

[functions.import-video]
verify_jwt = false

[functions.generate-study-quiz]
verify_jwt = false